---

# ------------------------------------------------------------------------------
# Ensure necessary variables from other roles
# ------------------------------------------------------------------------------
- name: Include redis variables for monitoring
  ansible.builtin.include_vars: ../../roles/redis/defaults/main.yml
  when: redis_instances is not defined

- name: Include nomad variables for monitoring
  ansible.builtin.include_vars: ../../roles/nomad/defaults/main.yml
  when: nomad_jobs is not defined

# ------------------------------------------------------------------------------
# Ensure to include master and agent setups
# ------------------------------------------------------------------------------
- name: Include monitoring master setup
  ansible.builtin.include_tasks: master.yml
  when: groups['all'] | length() == 1 or inventory_hostname in groups['monitoring']

- name: Include monitoring agent setup
  ansible.builtin.include_tasks: agent.yml

# ------------------------------------------------------------------------------
# Ensure to include steps to setup database monitoring
# ------------------------------------------------------------------------------
- name: Ensure monitoring can connect to the database
  ansible.builtin.include_tasks: database.yml

# ------------------------------------------------------------------------------
# Ensure to install python rpm package since checkmk has rpm as requirement
# ------------------------------------------------------------------------------
- name: Install python3-rpm
  ansible.builtin.apt:
    name: python3-rpm
    state: present
