---

# ------------------------------------------------------------------------------
# Install master package
# ------------------------------------------------------------------------------
- name: Fetch checkmk master deb file checksum
  ansible.builtin.uri:
    url: "{{ ansible_local.general_facts.general.url }}/service/rest/v1/search?repository={{ ansible_local.general_facts.general.repo_url_part }}&name={{ ansible_local.general_facts.monitoring.path }}/check-mk-raw-{{ ansible_local.general_facts.monitoring.version }}.{{ ansible_distribution_release }}_amd64.deb"
    use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
  environment:
    https_proxy: "{{ http_proxy | default() }}"
  register: checkmk_shasum
  when: not ansible_local.offline_mode.stat.exists

- name: Download Checkmk master deb file
  ansible.builtin.get_url:
    url: "{{ ansible_local.general_facts.general.url }}/repository/{{ ansible_local.general_facts.general.repo_url_part }}{{ ansible_local.general_facts.monitoring.path }}/check-mk-raw-{{ ansible_local.general_facts.monitoring.version }}.{{ ansible_distribution_release }}_amd64.deb"
    dest: "/var/cache/downloads/check-mk-raw-{{ ansible_local.general_facts.monitoring.version }}.{{ ansible_distribution_release }}_amd64.deb"
    checksum: "sha256:{{ checkmk_shasum.json['items'][0]['assets'][0]['checksum']['sha256'] }}"
    mode: 0440
    use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
  environment:
    https_proxy: "{{ http_proxy | default() }}"
  when: not ansible_local.offline_mode.stat.exists

- name: Install checkmk master
  ansible.builtin.apt:
    deb: "/var/cache/downloads/check-mk-raw-{{ ansible_local.general_facts.monitoring.version }}.{{ ansible_distribution_release }}_amd64.deb"

# ------------------------------------------------------------------------------
# Install acl to successfully switch user
# ------------------------------------------------------------------------------
- name: Install acl pkg
  ansible.builtin.apt:
    name: acl
    state: present

# ------------------------------------------------------------------------------
# Create checkmk site and configure it correctly
# ------------------------------------------------------------------------------
- name: Check if checkmk site exists
  ansible.builtin.command: "omd sites"
  register: checkmk_sites
  changed_when: "checkmk_site not in checkmk_sites.stdout"
  notify: Create checkmk site

- name: Check if omd site requires update
  ansible.builtin.command: "omd version {{ checkmk_site }}"
  register: omd_site_version
  changed_when: "ansible_local.general_facts.monitoring.version not in omd_site_version.stdout"
  when: checkmk_sites is not changed
  notify:
    - Update omd site
    - Ansible facts reload

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Allow checkmk site user to use cron
  ansible.builtin.template:
    src: master_confs/cron-allow.j2
    dest: /etc/cron.allow
    owner: root
    group: root
    mode: 0644

- name: Ensure checkmk omd site is configured as wished
  ansible.builtin.template:
    src: master_confs/omd-site.conf.j2
    dest: /opt/omd/sites/{{ checkmk_site }}/etc/omd/site.conf
    owner: "{{ checkmk_site }}"
    group: "{{ checkmk_site }}"
    mode: 0644
  notify: Reload omd site apache config

- name: Ensure checkmk apache listen port is configured as wished
  ansible.builtin.template:
    src: master_confs/apache-listen-ports.conf.j2
    dest: /opt/omd/sites/{{ checkmk_site }}/etc/apache/listen-port.conf
    owner: "{{ checkmk_site }}"
    group: "{{ checkmk_site }}"
    mode: 0644
  notify: Reload omd site apache config

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure the checkmk site is up and running
  block:
    - name: Check the state of the checkmk pages
      ansible.builtin.command: "omd status {{ checkmk_site }}"
      changed_when: false
  rescue:
    - name: Start checkmk site
      ansible.builtin.command: "omd start {{ checkmk_site }}"
      changed_when: false

- name: Create the SSL certificate
  ansible.builtin.template:
    src: master_confs/server_and_intermediate_and_root.crt.j2
    dest: /etc/ssl/certs/server_and_intermediate_and_root.crt
    mode: 0640
  notify: Restart apache2

- name: Configure /etc/apache2/ports.conf
  ansible.builtin.copy:
    src: apache-ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart apache2

- name: Configure /etc/apache2/conf-enabled/security.conf
  ansible.builtin.copy:
    src: apache-security.conf
    dest: /etc/apache2/conf-enabled/security.conf
    owner: root
    group: root
    mode: 0755
  notify: Restart apache2

- name: Ensure apache module ssl is enabled
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ssl
    - headers
    - rewrite
  notify: Restart apache2

- name: Deploy apache2 site configuration
  ansible.builtin.template:
    src: master_confs/apache-site.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart apache2

- name: Create symlink for apache2 site configuration
  ansible.builtin.file:
    src: /etc/apache2/sites-available/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: link
  notify: Restart apache2

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure apache2 service is enabled and running
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Install logrotate job for apache2 logs
  ansible.builtin.copy:
    src: apache2-log
    dest: /etc/logrotate.d/apache2
    owner: root
    group: root
    mode: 0644

# ------------------------------------------------------------------------------
# Ensure passwords are set correctly
# ------------------------------------------------------------------------------
- name: Ensure cmkadmin password is correctly defined and up to date
  block:
    - name: Check cmkadmin password
      ansible.builtin.command: "htpasswd -bv /opt/omd/sites/{{ checkmk_site }}/etc/htpasswd cmkadmin {{ monitoring_cmkadmin_password }}"
      register: check_cmkadmin_pw
      changed_when: false
      no_log: true
  rescue:
    - name: Update cmkadmin password
      ansible.builtin.command: "htpasswd -bB /opt/omd/sites/{{ checkmk_site }}/etc/htpasswd cmkadmin {{ monitoring_cmkadmin_password }}"
      changed_when: false
      no_log: true

# ------------------------------------------------------------------------------
# Set Facts for checkmk users with authorization secrets
# ------------------------------------------------------------------------------
- name: Deploy ansible facts for checkmk users with authorization secrets
  ansible.builtin.template:
    src: master_confs/checkmk.fact.j2
    dest: "/etc/ansible/facts.d/checkmk.fact"
    mode: 0755
    owner: root
    group: root
  notify: Ansible facts reload

# ------------------------------------------------------------------------------
# Allow teamwire user to switch to monitoring site user
# ------------------------------------------------------------------------------
- name: Configure sudo to allow teamwire user to switch to monitoring site user
  ansible.builtin.template:
    src: master_confs/sudo-10-monitoring-master.j2
    dest: "/etc/sudoers.d/10-monitoring-master"
    mode: 0440
    owner: root
    group: root
    validate: /usr/sbin/visudo -cf %s

# ------------------------------------------------------------------------------
# Configure checkmk
# ------------------------------------------------------------------------------
- name: Configure master conf.d/wato files
  ansible.builtin.template:
    src: "master_confs/{{ item }}.j2"
    dest: "/opt/omd/sites/{{ checkmk_site }}/etc/check_mk/conf.d/wato/{{ item }}"
    owner: "{{ checkmk_site }}"
    group: "{{ checkmk_site }}"
    mode: '0660'
  with_items:
    - hosts.mk
    - rules.mk
    - tags.mk
    - notifications.mk
  notify: Update checkmk config

- name: Configure available multisite Tags
  ansible.builtin.template:
    src: master_confs/multisite_tags.mk.j2
    dest: /opt/omd/sites/{{ checkmk_site }}/etc/check_mk/multisite.d/wato/tags.mk
    owner: "{{ checkmk_site }}"
    group: "{{ checkmk_site }}"
    mode: '0660'
  notify: Update checkmk config

# ------------------------------------------------------------------------------
# Download extra MKP Packages from checkmk exchange
# ------------------------------------------------------------------------------
- name: Fetch checkmk master deb file checksum
  ansible.builtin.uri:
    url: "{{ ansible_local.general_facts.general.url }}/service/rest/v1/search?repository={{ ansible_local.general_facts.general.repo_url_part }}&name={{ ansible_local.general_facts.monitoring.sslcertificate_path }}/sslcertificates-{{ ansible_local.general_facts.monitoring.sslcertificate_version }}.mkp"
    use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
  environment:
    https_proxy: "{{ http_proxy | default() }}"
  register: checkmk_sslcertificate_shasum
  when: not ansible_local.offline_mode.stat.exists

- name: Download checkmk sslcertificate mkp
  ansible.builtin.get_url:
    url: "{{ ansible_local.general_facts.general.url }}/repository/{{ ansible_local.general_facts.general.repo_url_part }}{{ ansible_local.general_facts.monitoring.sslcertificate_path }}/sslcertificates-{{ ansible_local.general_facts.monitoring.sslcertificate_version }}.mkp"
    dest: "/var/cache/downloads/sslcertificates-{{ ansible_local.general_facts.monitoring.sslcertificate_version }}.mkp"
    checksum: "sha256:{{ checkmk_sslcertificate_shasum.json['items'][0]['assets'][0]['checksum']['sha256'] }}"
    mode: 0444
    use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
  environment:
    https_proxy: "{{ http_proxy | default() }}"
  when: not ansible_local.offline_mode.stat.exists

- name: Check mkp sslcertificate version
  ansible.builtin.command: "mkp show sslcertificates {{ ansible_local.general_facts.monitoring.sslcertificate_version }}"
  become_user: "tw_monitoring"
  become_flags: -i
  environment:
    PATH: "/omd/sites/tw_monitoring/lib/perl5/bin:/omd/sites/tw_monitoring/local/bin:/omd/sites/tw_monitoring/bin:/omd/sites/tw_monitoring/local/lib/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  register: check_mkp_sslcertificates
  changed_when: "'No such package' in check_mkp_sslcertificates.stderr"
  failed_when: "check_mkp_sslcertificates.stderr not in [ 'No such package: sslcertificates ' + ansible_local.general_facts.monitoring.sslcertificate_version, '' ]"
  notify: Install mkp package

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure to create link to be able to download mkp plugins to agent
  ansible.builtin.file:
    src: "{{ monitoring_master_custom_plugin_dir }}{{ item }}"
    dest: "{{ monitoring_master_plugin_dir }}{{ item }}"
    state: link
  with_items: "{{ monitoring_custom_agent_plugins }}"
