---

# ------------------------------------------------------------------------------
# Include Tasks for reverse proxy
# ------------------------------------------------------------------------------
- name: Include Tasks for reverse proxy
  ansible.builtin.include_tasks: reverse-proxy.yml

# ------------------------------------------------------------------------------
# Create Checkmk Container Mountpoints
# ------------------------------------------------------------------------------
- name: Ensure to create checkmk mountpoint folder
  ansible.builtin.file:
    path: "{{ checkmk_mountpoint }}"
    state: directory
    owner: 1000
    group: 1000
    mode: 0755

- name: Create Directory for container internal Postfix configuration
  ansible.builtin.file:
    path: "{{ postfix_mountpoint }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy container internal postfix master.cf
  ansible.builtin.copy:
    src: postfix-master.cf
    dest: "{{ postfix_mountpoint }}/master.cf"
    owner: root
    group: root
    mode: 0644

- name: Fixup the checkmk docker entrypoint script
  ansible.builtin.copy:
    src: fix-docker-entrypoint-checkmk_container.sh
    dest: /usr/local/bin/fix-docker-entrypoint-checkmk_container.sh
    owner: root
    group: root
    mode: 0755

- name: Copy script to deactivate the xinetd port inside the checkmk container for the agent
  ansible.builtin.copy:
    src: kill-xinetd-checkmk_container.sh
    dest: /usr/local/bin/kill-xinetd-checkmk_container.sh
    owner: root
    group: root
    mode: 0755

# ------------------------------------------------------------------------------
# Setup checkmk master docker container
# ------------------------------------------------------------------------------
- name: Retrieve the checkmk master container
  community.docker.docker_image:
    name: "{{ ansible_local.general_facts.monitoring.container }}"
    source: pull
    state: present
  when: not ansible_local.offline_mode.stat.exists

- name: Setup checkmk master docker container
  community.docker.docker_container:
    name: checkmk
    image: "{{ ansible_local.general_facts.monitoring.container }}"
    state: started
    restart_policy: always
    network_mode: host
    volumes:
      - "/usr/local/bin/fix-docker-entrypoint-checkmk_container.sh:/docker-entrypoint.sh"
      - "/usr/local/bin/kill-xinetd-checkmk_container.sh:/docker-entrypoint.d/pre-start/kill-xinetd-checkmk_container.sh"
      - "{{ checkmk_mountpoint }}:/omd/sites"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/hosts:/etc/hosts:ro"
      - "/var/cache/downloads:/var/cache/downloads:ro"
      - "{{ postfix_mountpoint }}/master.cf:/etc/postfix/master.cf"
    env:
      CMK_SITE_ID: "{{ checkmk_site }}"
      MAIL_RELAY_HOST: "[127.0.1.1]:25"

# ------------------------------------------------------------------------------
# Ensure omd site is created before continueing configure
# ------------------------------------------------------------------------------
- name: Check omd site status
  community.docker.docker_container_exec:
    container: checkmk
    command: bash -c "source ~/.profile && omd status"
  register: check_omd_site_status
  until: "checkmk_site in check_omd_site_status.stdout"
  retries: 12
  delay: 10
  failed_when: "checkmk_site not in check_omd_site_status.stdout"
  changed_when: false

- name: Ensure the container has enough time to create all necessary files
  ansible.builtin.pause:
    seconds: 10
  when: check_omd_site_status.attempts > 1

# ------------------------------------------------------------------------------
# Configure omd site
# ------------------------------------------------------------------------------
- name: Ensure checkmk omd site is configured as wished
  ansible.builtin.template:
    src: master_confs/omd-site.conf.j2
    dest: "{{ checkmk_mountpoint }}/{{ checkmk_site }}/etc/omd/site.conf"
    owner: 1000
    group: 1000
    mode: 0644
  notify: Restart checkmk container

- name: Ensure checkmk apache listen port is configured as wished
  ansible.builtin.template:
    src: master_confs/apache-listen-ports.conf.j2
    dest: "{{ checkmk_mountpoint }}/{{ checkmk_site }}/etc/apache/listen-port.conf"
    owner: 1000
    group: 1000
    mode: 0644
  notify: Restart checkmk container

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

# ------------------------------------------------------------------------------
# Ensure passwords are set correctly
# ------------------------------------------------------------------------------
- name: Ensure cmkadmin password is correctly defined and up to date
  block:
    - name: Check cmkadmin password
      community.docker.docker_container_exec:
        container: checkmk
        command: "htpasswd -bv /omd/sites/{{ checkmk_site }}/etc/htpasswd cmkadmin {{ monitoring_cmkadmin_password }}"
      changed_when: false
      no_log: true
  rescue:
    - name: Update cmkadmin password
      community.docker.docker_container_exec:
        container: checkmk
        command: "htpasswd -bB /omd/sites/{{ checkmk_site }}/etc/htpasswd cmkadmin {{ monitoring_cmkadmin_password }}"
      changed_when: false
      no_log: true

# ------------------------------------------------------------------------------
# Configure checkmk
# ------------------------------------------------------------------------------
- name: Read nomad management token to check nomad jobs
  ansible.builtin.command: vault kv get -field=value secret/nomad/management_token
  register: management_token
  changed_when: false
  delegate_to: "{{ groups.hashi_servers | sort | first }}"
  when: groups['all'] | length > 1

- name: Configure master conf.d/wato files
  ansible.builtin.template:
    src: "master_confs/{{ item }}.j2"
    dest: "{{ checkmk_mountpoint }}/{{ checkmk_site }}/etc/check_mk/conf.d/wato/{{ item }}"
    owner: 1000
    group: 1000
    mode: 0660
  with_items:
    - hosts.mk
    - rules.mk
    - tags.mk
    - notifications.mk
  notify: Update checkmk config

- name: Configure available multisite Tags
  ansible.builtin.template:
    src: master_confs/multisite_tags.mk.j2
    dest: "{{ checkmk_mountpoint }}/{{ checkmk_site }}/etc/check_mk/multisite.d/wato/tags.mk"
    owner: 1000
    group: 1000
    mode: 0660
  notify: Update checkmk config

# ------------------------------------------------------------------------------
# Download extra MKP Packages from checkmk exchange
# ------------------------------------------------------------------------------
- name: Fetch checkmk master deb file checksum
  ansible.builtin.uri:
    url: "{{ ansible_local.general_facts.monitoring.sslcertificate_sha256 }}"
    use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
  environment:
    https_proxy: "{{ http_proxy | default() }}"
  register: checkmk_sslcertificate_shasum
  when: not ansible_local.offline_mode.stat.exists

- name: Download checkmk sslcertificate mkp
  ansible.builtin.get_url:
    url: "{{ ansible_local.general_facts.monitoring.sslcertificate_url }}"
    dest: "/var/cache/downloads/sslcertificates-{{ ansible_local.general_facts.monitoring.sslcertificate_version }}.mkp"
    checksum: "sha256:{{ checkmk_sslcertificate_shasum.json['items'][0]['assets'][0]['checksum']['sha256'] }}"
    mode: 0444
    use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
  environment:
    https_proxy: "{{ http_proxy | default() }}"
  when: not ansible_local.offline_mode.stat.exists

- name: Check mkp sslcertificate version
  community.docker.docker_container_exec:
    container: checkmk
    command: bash -c "source ~/.profile && mkp show sslcertificates {{ ansible_local.general_facts.monitoring.sslcertificate_version }}"
    user: "{{ checkmk_site }}"
  register: check_mkp_sslcertificates
  changed_when: "'No such package' in check_mkp_sslcertificates.stderr"
  failed_when: "check_mkp_sslcertificates.stderr not in [ 'No such package: sslcertificates ' + ansible_local.general_facts.monitoring.sslcertificate_version, '' ]"
  notify: Install mkp package

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Check if file links for mkp plugins exists
  ansible.builtin.find:
    paths: /var/lib/docker/
    patterns: "{{ item }}"
    file_type: link
    recurse: true
  register: custom_plugin_links
  with_items: "{{ monitoring_custom_agent_plugins }}"

- name: Ensure to create link to be able to download mkp plugins to agent
  community.docker.docker_container_exec:
    container: checkmk
    command: "ln -s /omd/sites/{{ checkmk_site }}/local/share/check_mk/agents/plugins/{{ item }} /omd/sites/{{ checkmk_site }}/share/check_mk/agents/plugins/{{ item }}"
  when: "custom_plugin_links.results | selectattr('item', 'equalto', item) | map(attribute='files') | sum(start=[]) | selectattr('path', 'search', 'share/check_mk/agents/plugins/' + item) == []"
  with_items: "{{ monitoring_custom_agent_plugins }}"

# ------------------------------------------------------------------------------
# Set Facts for checkmk users with authorization secrets
# Necessary for agent install
# ------------------------------------------------------------------------------
- name: Get checkmk container infos
  community.docker.docker_container_info:
    name: checkmk
  register: checkmk_container_info

- name: Get agent_registration secret
  ansible.builtin.slurp:
    src: "{{ checkmk_mountpoint }}/{{ checkmk_site }}/var/check_mk/web/agent_registration/automation.secret"
  register: agent_registration_user_secret

- name: Deploy ansible facts for checkmk users with authorization secrets
  ansible.builtin.template:
    src: master_confs/checkmk.fact.j2
    dest: "/etc/ansible/facts.d/checkmk.fact"
    mode: 0644
    owner: root
    group: root
  notify: Ansible facts reload

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
