---
frontend_haproxy_template: frontend_haproxy.cfg.j2
globals_haproxy_template: ../backend/templates/globals_haproxy.cfg.j2
websockets_enabled: "true"
haproxy_proc_count: "{{ 1 if 'frontend_servers' not in groups and groups['all'] | length() == 1 else ansible_facts.processor_count }}"

voip_turn_port: "{{ '5349' if ssl_server_certificate is defined and ssl_keyfile is defined else '3478' }}"
