---
- name: Save ocsp response into file # noqa no-handler
  ansible.builtin.command: /usr/local/src/ocsp.sh
  when:
    - ha_installed.changed
    - stat_ocspfile.stat.exists is true
  notify: Restart haproxy

- name: Stat ocsp file and register it
  ansible.builtin.stat:
    path: "{{ ocspfile_path }}"
  register: stat_ocspfile

- name: Flush ocsp # noqa no-handler
  ansible.builtin.meta: flush_handlers
  when:
    - ha_installed.changed
    - stat_ocspfile.stat.exists is true

- name: Enable ocsp in haproxy # noqa no-handler
  ansible.builtin.command: /usr/local/src/ocsp.sh
  when:
    - ha_installed.changed
    - stat_ocspfile.stat.exists is true
