---

# ------------------------------------------------------------------------------
# Define default variables
# ------------------------------------------------------------------------------
checkmk_site: "tw_monitoring"
checkmk_mountpoint: "/srv/checkmk"

# ------------------------------------------------------------------------------
# Define reverse Proxy Variables
# ------------------------------------------------------------------------------
nginx_mountpoint: "/srv/nginx"

# ------------------------------------------------------------------------------
# Define container internal postfix conf moutpoint
# ------------------------------------------------------------------------------
postfix_mountpoint: "/srv/postfix"

# ------------------------------------------------------------------------------
# Define Database related variables
# ------------------------------------------------------------------------------
monitoring_db_user: "monitor"

# ------------------------------------------------------------------------------
# Define Notifications related variables
# ------------------------------------------------------------------------------
monitoring_sender_address: "{{ sender_address.split('<')[1] | default(sender_address) | replace('>', '') }}"
monitoring_mail_subject_tag: "TW Monitoring:"
