---

# ------------------------------------------------------------------------------
# Define default site variables
# ------------------------------------------------------------------------------
checkmk_site: "tw_monitoring"
checkmk_master_ip: "{{ ansible_default_ipv4.address if groups['all'] | length == 1 else hostvars[groups['monitoring'] | first].private_ip }}"
checkmk_port: "8000"
checkmk_url: "https://{{ checkmk_master_ip }}:{{ checkmk_port }}/{{ checkmk_site }}/check_mk"

# ------------------------------------------------------------------------------
# Define Database related variables
# ------------------------------------------------------------------------------
monitoring_db_user: "monitor"

# ------------------------------------------------------------------------------
# Define Notifications related variables
# ------------------------------------------------------------------------------
monitoring_sender_address: "{{ sender_address.split('<')[1] | default(sender_address) | replace('>', '') }}"
monitoring_mail_subject_tag: "TW Monitoring:"
