---
- name: Unload fs modules
  ansible.builtin.command: "/sbin/modprobe -n -v {{ item }}"
  with_items:
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - vfat

- name: Restart kernel modules systemd
  ansible.builtin.systemd:
    name: systemd-modules-load.service
    state: restarted

- name: Permission handler
  ansible.builtin.command: "chmod 1777 /tmp" # noqa deprecated-command-syntax

- name: Reload sysctl options
  ansible.builtin.service:
    name: procps
    state: restarted
