---
- name: Unload fs modules
  ansible.builtin.command: "/sbin/modprobe -n -v {{ item }}"
  with_items:
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - vfat

- name: Restart kernel modules systemd
  ansible.builtin.systemd:
    name: systemd-modules-load.service
    state: restarted

- name: Permission handler
  ansible.builtin.command: "chmod 1777 /tmp" # noqa deprecated-command-syntax

- name: Reload sysctl options
  ansible.builtin.service:
    name: procps
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart MariaDB
  ansible.builtin.service:
    name: mysql
    state: restarted
  throttle: 1
  with_items: "{{ hostvars[groups['database_servers'] | sort | first].show_galera_cluster_size.query_result if groups['all'] | length > 1 }}"
  when:
    - groups['all'] | length == 1 or
      ( "database_servers" in groups and item.Value != "0" )

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: Restart sshd service
  ansible.builtin.systemd:
    name: sshd
    state: restarted
