---
registry_dir: /data/registry
registry_config: registry-config.yml.j2
use_teamwire_registry: true

local_registry_username: "teamwire"

# Set repo url part to external/internal
repo_url_part: "{{ 'internal' if use_internal_package_repository is defined and use_internal_package_repository is truthy else 'external' }}"

# Set variables necessary to get the docker package versions
docker_package_file_url: "https://repo.teamwire.eu/{{ repo_url_part }}/ftp/docker_packages.txt"
docker_checksum_package_file_url: "https://repo.teamwire.eu/{{ repo_url_part }}/ftp/checksum_docker_packages"
docker_package_file_path: "/var/cache/downloads/docker_packages.txt"
docker_checksum_file_path: "/var/cache/downloads/checksum_docker_packages"
