---
# Mydumper must be installed separatly when mydumper is installed on existing installations
- name: Install mydumper independent from task install mariadb
  ansible.builtin.apt:
    name: mydumper
    state: present
  when: ansible_distribution_release == "bookworm"

- name: Fetch and install mydumper package
  block:
    - name: Fetch mydumper debian file checksum
      ansible.builtin.uri:
        url: "{{ ansible_local.general_facts.db.mydumper_sha256 }}"
        use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
      environment:
        https_proxy: "{{ http_proxy | default() }}"
      register: mydumper_shasum
      when: not ansible_local.offline_mode.stat.exists

    - name: Download mydumper debian file
      ansible.builtin.get_url:
        url: "{{ ansible_local.general_facts.db.mydumper_url }}"
        dest: "/var/cache/downloads/mydumper_{{ ansible_local.general_facts.db.mydumper_version }}.{{ ansible_distribution_release }}_amd64.deb"
        checksum: "sha256:{{ mydumper_shasum.json['items'][0]['assets'][0]['checksum']['sha256'] }}"
        mode: 0440
        use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
      environment:
        https_proxy: "{{ http_proxy | default() }}"
      when: not ansible_local.offline_mode.stat.exists

    - name: Install mydumper
      ansible.builtin.apt:
        deb: "/var/cache/downloads/mydumper_{{ ansible_local.general_facts.db.mydumper_version }}.{{ ansible_distribution_release }}_amd64.deb"
  when: ansible_distribution_release != "bookworm"

- name: Implement Backup and Restorescript
  ansible.builtin.template:
    src: backup_restore_db.sh.j2
    dest: /usr/local/bin/backup_restore_db.sh
    owner: root
    group: root
    mode: 0755
