---

# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - name: Include vault role
      ansible.builtin.include_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/vault"
        tasks_from: secrets
      when:
        - ansible_local.vault is defined
        - ansible_local.vault.initialized == "true"
        - secrets_read is not defined

- name: Include offline installation check
  hosts: local:management_servers
  tasks:
    - name: Import check offline installation task
      ansible.builtin.include_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/common"
        tasks_from: check_offline_installation

- name: Include go
  hosts: local:management_servers
  tasks:
    - name: Include go role
      ansible.builtin.include_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/go"
