---
# Please refer here: https://github.com/ansible/ansible/issues/30901 why `inventory_dir` is
# sometimes not possible to use
- name: Configure housekeeping for management server(s)
  hosts: local:management_servers
  tasks:

  - name: Include housekeeping role
    ansible.builtin.include_role:
      name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/housekeeping"
