---
- name: Configure logging for loghost server(s)
  hosts: loghost
  tasks:
    - name: Configure the logging server
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/loghost"
      when:
        - groups['all'] | length() > 1
