---

# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - name: Include vault role
      ansible.builtin.include_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/vault"
        tasks_from: secrets
      when:
        - ansible_local.vault is defined
        - ansible_local.vault.initialized == "true"
        - secrets_read is not defined

- name: Clean up icinga
  hosts: all
  tasks:
    - name: Cleanup icinga
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/housekeeping"
        tasks_from: cleanup_monitoring
      when: config_done is defined


- name: Deploy monitoring system
  hosts: all
  tasks:
    - name: Include monitoring role
      ansible.builtin.include_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/monitoring"
      when:
        - config_done is defined
        - enable_monitoring is defined and enable_monitoring | lower in [ "yes", "true" ]
