---

# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - name: Include roles/vault role
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/vault"
        tasks_from: secrets
      when:
        - ansible_local.vault is defined
        - ansible_local.vault.initialized == "true"
        - secrets_read is not defined

- name: Include offline installation check
  hosts: local:management_servers:voip_servers:backend_servers:video_servers
  tasks:
    - name: Import check offline installation task
      ansible.builtin.include_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/common"
        tasks_from: check_offline_installation

# Please refer here: https://github.com/ansible/ansible/issues/30901 why `inventory_dir` is
# sometimes not possible to use
- name: Configure voip for management server(s)
  hosts: local:management_servers
  tasks:
    - name: Include voip main.yml for management_server
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/voip"
      when:
        - enable_voip is defined
        - enable_voip | string() == 'true'

    - name: Include voip_servers for management_server
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/voip"
        tasks_from: voip_servers.yml
      when:
        - groups['all'] | length > 1
        - enable_voip is defined
        - enable_voip | lower == 'true'
        - "'video_servers' not in group_names"

- name: Configure turn volume for voip server(s)
  hosts: voip_servers
  tasks:
    - name: Import tasks for turn volume creation
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/voip"
        tasks_from: turn_volume.yml
      when:
        - enable_voip is defined
        - enable_voip | string() == 'true'
        - enable_stun is defined
        - enable_stun | string() == 'true'
        - ssl_server_certificate is defined
        - ssl_keyfile is defined
        - groups['all'] | length > 1

- name: Configure voip for voip server(s)
  hosts: voip_servers
  tasks:
    - name: Import voip_servers tasks for voip_servers
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/voip"
        tasks_from: voip_servers.yml
      when:
        - enable_voip is defined
        - enable_voip | string() == 'true'
        - groups['all'] | length == 1

- name: Configure voip for voip server(s)
  hosts: voip_servers
  tasks:
    - name: Import voip_servers tasks for voip_servers
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/voip"
        tasks_from: voip_servers.yml
      when:
        - enable_voip is defined
        - enable_voip | string() == 'true'
        - groups['all'] | length  > 1

- name: Configure voip for backend server(s)
  hosts: backend_servers
  tasks:
    - name: Import voip_servers tasks for backend servers
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/voip"
        tasks_from: voip_servers.yml
      when:
        - enable_voip is defined
        - enable_voip | string() == 'true'
        - groups['all'] | length  > 1
        - groups['video_servers'] is not defined
        - enable_jvb_cluster is defined
        - enable_jvb_cluster | string() == 'true'

- name: Configure voip for video server(s)
  hosts: video_servers
  tasks:
    - name: Import voip_servers tasks for video_servers
      ansible.builtin.import_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/voip"
        tasks_from: voip_servers.yml
      when:
        - enable_voip is defined
        - enable_voip | string() == 'true'
        - groups['all'] | length  > 1
        - enable_jvb_cluster is defined
        - enable_jvb_cluster | string() == 'true'

- name: Configure additional hosts for voip server(s)
  hosts: voip_servers
  tasks:
    - name: Import add_additional_host tasks for voip_servers
      ansible.builtin.import_tasks: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/backend/tasks/add_additional_host.yml"
      when:
        - enable_voip is defined
        - enable_voip | string() == 'true'
        - groups['all'] | length > 1

- name: Configure additional hosts for video server(s)
  hosts: video_servers
  tasks:
    - name: Import add_additional_host for video_servers
      ansible.builtin.import_tasks: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/backend/tasks/add_additional_host.yml"
      when:
        - enable_voip is defined
        - enable_voip | string() == 'true'
        - groups['all'] | length > 1
