#!/bin/sh

IMAGES="teamwire/backend teamwire/web-screenshot-server teamwire/notification-server"
CONTAINERS="teamwire_screenshot_server teamwire_notification_server teamwire_beat teamwire_worker teamwire_backend"

help() {
	echo "Command line options:"
	echo
	echo "--help      Show help"
	echo "--migrate   Run database migrations"
	echo "--pull TAG  Pull containers for a given tag"
	echo "--rm        Remove all stopped Teamwire containers"
	echo "--stop      Stop all running Teamwire containers"
	echo "--start     Start all stopped Teamwire containers"
	echo "--tag TAG   Use given tag for production"
}

pull_images() {
	echo "Pulling Teamwire container images for version $TAG"
	echo
	for IMAGE in $IMAGES; do
		docker pull "$IMAGE":"$TAG"
	done
}

remove_containers() {
	for CONTAINER in $CONTAINERS; do
		docker rm "$CONTAINER"
	done
}

run_migrations() {
	CONFIG_FILE=~teamwire/platform/ansible/group_vars/all
	MYSQL_HOST="$(awk '/^mysql_host/ { print $2 }' "$CONFIG_FILE")"                      2> /dev/null
	MYSQL_PORT="$(awk '/^mysql_port/ { print $2 }' "$CONFIG_FILE")"                      2> /dev/null
	MYSQL_PASS="$(awk '/^teamwire_db_password/ { print $2 }' "$CONFIG_FILE")"            2> /dev/null
	AESKEY="$(awk '/aes_key:/ { print $2 }' "$CONFIG_FILE" | sed 's|^\"\(.*\)\"$|\1|' )" 2> /dev/null

	if [ -z "$MYSQL_HOST" ]; then
		MYSQL_HOST=$(ifconfig docker0 | awk -F'[ :]+' '/inet addr/{print $4}')
	fi

	if [ -z "$MYSQL_PORT" ]; then
		MYSQL_PORT=3306
	fi

	if [ -z "$MYSQL_PASS" ] || [ -z "$AESKEY" ] ; then
		echo "Cannot read required parameters from $CONFIG_FILE."
		echo "Please ensure the file exists and the database is configured."
		exit 1
	fi

	ERROR_LOG="$(tempfile)"

	echo "Running database migrations"
	echo
	docker run --rm -e MODE=migration -e MYSQL_HOST="$MYSQL_HOST" \
		-e MYSQL_PORT="$MYSQL_PORT" -e MYSQL_PASSWORD="$MYSQL_PASS" \
		-e AESKEY="$AESKEY" teamwire/backend:prod 2> "$ERROR_LOG" | egrep -v '^(.+)='

	if [ $? -gt 0 ] ; then
		cat "$ERROR_LOG"
	fi
	rm -f "$ERROR_LOG"
}

tag_images() {
	echo "Using $TAG as production version"
	for IMAGE in $IMAGES; do
		docker tag -f "$IMAGE":"$TAG" "$IMAGE":prod
	done
}

stop_containers() {
	for CONTAINER in $CONTAINERS; do
		# First check if the container was started by upstart
		if sudo initctl status "$CONTAINER" | grep -q 'running' ; then
			sudo initctl stop "$CONTAINER"
		elif docker ps -qf name="$CONTAINER" | egrep -q '^.+$' ; then
			docker stop "$CONTAINER"
		fi
	done
}

start_containers() {
	for CONTAINER in $CONTAINERS; do
		sudo initctl start "$CONTAINER"
	done
}

TAG=""
TASK=""
while [ $# -gt 0 ] ; do
	case "$1" in
		-h|--help)
			help
			exit
			;;
		-m|--migrate)
			TASK="run_migrations"
			;;
		-p|--pull)
			TASK="pull_images"
			TAG_REQUIRED=yes
			;;
		-r|--rm)
			TASK="remove_containers"
			;;
		--start)
			TASK="start_containers"
			;;
		-s|--stop)
			TASK="stop_containers"
			;;
		-t|--tag)
			TASK="tag_images"
			TAG_REQUIRED=yes
			;;
		*)
			TAG="$1"
			;;
	esac
	shift
done

if [ -z "$TASK" ] ; then
	echo "Mission operation"
	echo
	help
	exit 1
fi

if [ "$TAG_REQUIRED" = "yes" ] && [ -z "$TAG" ] ; then
	echo "Please specify a release tag!"
	echo
	help
	exit 1
fi

$TASK
