#!/bin/sh

CONTAINERS="teamwire/backend teamwire/web-screenshot-server teamwire/notification-server"

help() {
	echo "Command line options:"
	echo
	echo "--help	Show help"
	echo "--pull	Pull containers for a given tag"
	echo "--tag	Use given tag for production"
}

pull_containers() {
	echo "Pulling Teamwire containers for version $TAG"
	for CONTAINER in $CONTAINERS; do
		docker pull "$CONTAINER":"$TAG"
	done
}

tag_containers() {
	echo "Using $TAG as production version"
	for CONTAINER in $CONTAINERS; do
		docker tag -f "$CONTAINER":"$TAG" "$CONTAINER":prod
	done
}


TAG=""
TASK=""
while [ $# -gt 0 ] ; do
	case "$1" in
		-h|--help)
			help
			exit
			;;
		-p|--pull)
			TASK="pull_containers"
			;;
		-t|--tag)
			TASK="tag_containers"
			;;
		*)
			TAG="$1"
			;;
	esac
	shift
done

if [ -z "$TASK" ] ; then
	echo "Mission operation"
	help
	exit 1
fi

if [ -z "$TAG" ] ; then
	echo "Please specify a tag!"
	exit 1
fi

$TASK
