---
mysql_databases:
  prod:
    dbname: "{{ teamwire_db_name | default('teamwire') }}"
    username: "{{ teamwire_db_user | default('teamwire') }}"
    password: "{{ teamwire_db_password }}"

optimizer_search_depth_value: 0

# 50-server.cnf vars
bind_address: "{{ private_ip if groups['all'] | length > 1 else '127.0.0.1' }}"
# max_allowed_packet: Previously 64M but not active!
max_allowed_packet: "1G"
max_connections: 512
optimizer_search_depth: 0

# 60-teamwire.cnf vars
enable_auto_calculation_innodb: true
innodb_buffer_pool_size: 0
