- name: Ensure dns_servers are configured before installing dnsmasq
  ansible.builtin.fail:
    msg: "DNS servers are not defined. Please check the configuration file"
  when:
    - config_done is defined
    - dns_servers is not defined

- name: Install dnsmasq
  ansible.builtin.apt:
    pkg: dnsmasq

- name: Ensure dnsmasq is started
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true

- name: Configure dnsmasq upstream DNS servers
  ansible.builtin.template:
    src: 20-upstream.j2
    dest: /etc/dnsmasq.d/20-upstream
    mode: 0644
    owner: root
    group: root
  when: dns_servers is defined
  notify: Restart dnsmasq

- name: Configure dnsmasq to listen on private_ip and localhost
  ansible.builtin.template:
    src: 01-address.j2
    dest: /etc/dnsmasq.d/01-address
    mode: 0644
    owner: root
    group: root
  when:
    - dns_servers is defined
    - enable_voip is defined and enable_voip | string() == 'true'
    - inventory_hostname not in groups['voip_servers']
  notify: Restart dnsmasq

- name: Resolve DNS using dnsmasq
  ansible.builtin.template:
    src: dns.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns.conf
    mode: '0644'
    owner: root
    group: root
  notify: Restart systemd-resolved

# Ensure we have a valid DNS configuration
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
