- name: Ensure dns_servers are configured before installing dnsmasq
  fail: msg="DNS servers are not defined. Please check the configuration file"
  when: config_done is defined and dns_servers is not defined

- name: Install dnsmasq
  apt: pkg=dnsmasq

- service:
    name: dnsmasq
    state: started
    enabled: true

- name: Configure dnsmasq upstream DNS servers
  template:
    src: 20-upstream.j2
    dest: /etc/dnsmasq.d/20-upstream
  when: dns_servers is defined
  notify: restart dnsmasq

- name: Resolve DNS using dnsmasq
  copy:
    content: "nameserver 127.0.0.1\n"
    dest: /etc/resolv.conf

- name: Configure DHCP client to use local DNS server
  lineinfile:
    regexp: "^#+prepend domain-name-servers"
    backrefs: yes
    line: "supersede domain-name-servers 127.0.0.1;"
    dest: /etc/dhcp/dhclient.conf
  notify: reload dhclient

# Ensure we have a valid DNS configuration
- meta: flush_handlers
