---
- name: Create local storage directory / NFS mount point
  ansible.builtin.file:
    path: /data
    owner: root
    group: root
    mode: 0755
    state: directory

# Mount external storage
- name: Install NFS client
  ansible.builtin.apt:
    pkg: nfs-common
    state: present
  when: external_storage_path is defined or ('storage_servers' in groups and groups['storage_servers'] | length == 1)

- name: Install GlusterFS client
  ansible.builtin.apt:
    pkg: glusterfs-client
    state: present
  when:
    - external_storage_path is not defined
    - "'storage_servers' in groups"
    - groups['storage_servers'] | length > 1

- name: Mount NFS share (external)
  ansible.posix.mount:
    name: /data
    fstype: nfs
    src: "{{ external_storage_path }}"
    state: mounted
  when: external_storage_path is defined

- name: Configure NFSv4 ID mapping domain
  ansible.builtin.lineinfile:
    dest: /etc/idmapd.conf
    regexp: '(# )?Domain = '
    line: 'Domain = {{ idmap_domain }}'
    backrefs: true
  when: external_storage_path is defined and idmap_domain is defined

- name: Comment NFSv4 ID mapping domain
  ansible.builtin.lineinfile:
    dest: /etc/idmapd.conf
    regexp: '(# )?Domain = '
    line: '# Domain = localdomain'
    backrefs: true
  when:
    - external_storage_path is defined
    - idmap_domain is not defined

- name: "Mount NFS share (cluster)"
  ansible.posix.mount:
    name: /data
    fstype: nfs
    src: "{{ groups['storage_servers'] | first }}:/data"
    state: mounted
  when:
    - external_storage_path is not defined
    - "'storage_servers' in groups"
    - groups['storage_servers'] | length == 1

- name: Register storage servers
  ansible.builtin.set_fact:
    storage: "{{ groups['storage_servers'] | sort | list }}"

- name: Mount GlusterFS share (cluster)
  ansible.posix.mount:
    name: /data
    fstype: glusterfs
    src: "{{ groups['storage_servers'] |sort |first }}:/data"
    opts: "{% for host in storage[1:] %}backupvolfile-server={{ host }},{% endfor %}direct-io-mode=disable"
    state: mounted
  when:
    - external_storage_path is not defined
    - "'storage_servers' in groups"
    - groups['storage_servers'] | length > 1
    - not inventory_hostname in groups['storage_servers']
