# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "teamwire/server"

  # The ssh user name used to connect to the created VM with "vagrant ssh"
  config.ssh.username = "teamwire"
  config.ssh.password = ""
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Disable the default shared folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Set server hostname
  config.vm.define "teamwire-server" do |server|
    server.vm.hostname = "teamwire-server"
  end

  # Configure a private static IP
  #config.vm.network "private_network", ip: "192.168.121.188"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider :vmware_fusion do |v|
    # Enable nested virtualisation
    v.vmx["vhv.enable"] = "TRUE"
    v.vmx["memsize"] = "1024"
    v.vmx["ethernet0.pcislotnumber"] = "33"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provider "libvirt" do |vm|
    vm.memory = 1024
    vm.cpu_mode = "host-passthrough"
  end

  # Enable provisioning with Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "../ansible/site.yml"
    ansible.become = true
    # ansible.verbose = 'vvv'
  end
end
