---
- name: Update timezone
  ansible.builtin.command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Restart NTP
  ansible.builtin.service:
    name: ntp
    state: restarted

- name: Reload sshd
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Rebuild postfix passwd map
  ansible.builtin.command: postmap /etc/postfix/sasl/passwd

- name: Rebuild postfix generic map
  ansible.builtin.command: postmap /etc/postfix/generic

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: New aliases
  ansible.builtin.command: newaliases

- name: Rebuild postfix domain map
  ansible.builtin.command: postmap /etc/postfix/virtual

- name: Reload dhclient
  ansible.builtin.command: pkill dhclient
  ignore_errors: true # noqa ignore-errors
  notify: Reload dhclient step 2

- name: Reload dhclient step 2
  ansible.builtin.command: dhclient
  ignore_errors: true # noqa ignore-errors

- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload # noqa command-instead-of-module
