---
- name: Install GlusterFS server and client
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - glusterfs-server
    - glusterfs-client
    - rpcbind

- name: Create GlusterFS brick
  ansible.builtin.file:
    path: "{{ gluster_brick_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Start GlusterFS server
  ansible.builtin.service:
    name: glusterd
    state: started
    enabled: true

- name: Create Gluster volume
  gluster.gluster.gluster_volume:
    name: "{{ gluster_volume }}"
    bricks: "{{ gluster_brick_dir }}"
    cluster: "{{ groups[glusterfs_peer_group] }}"
    replicas: "{{ groups[glusterfs_peer_group] | count }}"
    force: true
    state: present
  run_once: true

- name: Mount GlusterFS from localhost
  ansible.posix.mount:
    name: /data
    src: "{{ inventory_hostname }}:{{ gluster_volume }}"
    fstype: glusterfs
    opts: defaults,_netdev,backupvolfile-server={{ groups[glusterfs_peer_group] | difference([inventory_hostname]) | first }}
    state: mounted
  when: inventory_hostname in groups[glusterfs_peer_group]

- name: Install logrotate job for glusterfs-common logs
  ansible.builtin.copy:
    src: glusterfs-common-log
    dest: /etc/logrotate.d/glusterfs-common
    owner: root
    group: root
    mode: 0644
