---
- name: Check if installing a storage cluster
  ansible.builtin.set_fact:
    glusterfs_cluster: true
  when: '"storage_servers" in groups and groups["storage_servers"] | length > 1'

- name: Include single
  ansible.builtin.include_tasks: single.yml
  when: glusterfs_cluster is not defined

- name: Include glusterfs
  ansible.builtin.include_tasks: glusterfs.yml
  when: glusterfs_cluster is defined
