---
- name: Install NFS server
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-kernel-server
    - rpcbind
  notify: Restart NFS server

- name: Create the NFS root directory
  ansible.builtin.file:
    name: /data
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Write the NFS config
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: Reload NFS server
