- name: Restart icinga2
  ansible.builtin.service:
    name: icinga2
    state: restarted

- name: Restart nagios-nrpe-server
  ansible.builtin.service:
    name: nagios-nrpe-server
    state: restarted

- name: Restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Update apt
  ansible.builtin.apt:
    update_cache: true
  when: not ansible_local.offline_mode.stat.exists
