- name: Restart consul
  ansible.builtin.service:
    name: consul
    state: restarted

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Run resolvconf
  ansible.builtin.shell: resolvconf -u # noqa command-instead-of-shell
