---

# ------------------------------------------------------------------------------
# Ensure postfix is removed from existing installations
# ------------------------------------------------------------------------------
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Disable postfix
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: false
  when:
    - use_nullmailer is defined
    - use_nullmailer | lower == "true"
    - "'postfix' in ansible_facts.packages"

- name: Remove postfix
  ansible.builtin.apt:
    name: postfix
    state: absent
    purge: true
