---

# ------------------------------------------------------------------------------
# Ensure hashi-ui container is stopped
# ------------------------------------------------------------------------------
- name: Run hashi-ui in clustered setups
  community.docker.docker_container:
    name: hashi-ui
    state: absent
