---
nginx_http_port: 7080
nginx_https_port: 7443

voip_root_path: "/data/voip"
voip_jitsi_version: "{{ version }}"


voip_container_web: "teamwire/web2"
voip_container_prosody: "teamwire/prosody"
voip_container_jicofo: "teamwire/jicofo"
voip_container_jvb: "teamwire/jvb"
voip_container_turn: "teamwire/turn"

nomad_health_voip_interval: 15
nomald_health_voip_timeout: 2

voip_turn_port: "{{ '5349' if ssl_server_certificate is defined and ssl_keyfile is defined else '3478' }}"
