---
- name: Create local go src directory
  ansible.builtin.file:
    path: "/usr/local/src/go"
    state: directory
    mode: 0755

- name: Copy source code to local src dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/src/go/
    mode: 0644
    owner: teamwire
    group: teamwire
  with_items: "{{ gosource }}"
  register: copysrc

- name: Login to the docker registry
  community.docker.docker_login:
    registry_url: "{{ 'https://harbor.teamwire.eu' if use_teamwire_registry | default('true') | bool else 'https://index.docker.io/v1/' }}"
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
  when: not ansible_local.offline_mode.stat.exists

- name: Build golang binarys
  ansible.builtin.shell: docker run --rm -e GOFILE={{ item }} -v /usr/local/bin:/dest -v /usr/local/src/go:/src {{ 'harbor.teamwire.eu/' if use_teamwire_registry | default('true') | bool else '' }}teamwire/go-buildenv:latest # noqa command-instead-of-shell
  when: copysrc.changed # noqa no-handler
  with_items: "{{ gosource }}"
  become: true
