---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Create local registry credentials
  ansible.builtin.command: "htpasswd -Bbc {{ registry_dir }}/htpasswd {{ local_registry_username }} {{ local_registry_password }}"
  no_log: true

- name: Dearmor Docker repository key
  ansible.builtin.command: gpg --dearmor -o {{ (docker_signing_key.dest | splitext)[0] }}.gpg {{ docker_signing_key.dest }}
