---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart registry container
  community.docker.docker_container:
    name: docker-registry
    image: "{{ registry_version }}"
    state: started
    restart_policy: always
    restart: true
    network_mode: host
    log_driver: syslog
    log_options:
      tag: docker-registry
      syslog-facility: local6
    volumes: "{{ registry_dir }}:/var/lib/registry,{{ registry_dir }}/config.yml:/etc/docker/registry/config.yml"

- name: Dearmor Docker repository key
  ansible.builtin.command: gpg --dearmor -o {{ (docker_signing_key.dest | splitext)[0] }}.gpg {{ docker_signing_key.dest }}
