---
- name: Restart systemd Haproxy
  ansible.builtin.systemd:
    daemon_reload: true
    name: haproxy
    state: restarted
    enabled: true

- name: Reload HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded

- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
