---
- name: Ensure to stop the maxscale service
  ansible.builtin.service:
    name: maxscale
    enabled: false
    state: stopped
  when: inventory_hostname in groups['backend_servers']

- name: Install HAproxy
  ansible.builtin.apt:
    name: haproxy
    state: present

# This uses systemd's unit file drop-in override mechanism,
# allowing us to keep vendor's default service unit file together with our customizations
# https://manpages.debian.org/systemd/systemd.unit.5.en.html
- name: Adapt HAproxy service to split-configuration setup
  block:
    - name: Create HAproxy drop-in override directory
      ansible.builtin.file:
        path: /etc/systemd/system/haproxy.service.d
        state: directory
        mode: 0755
        owner: root
        group: root
      register: haproxy_systemd_service_unit_override

    - name: Adapt HAproxy service to split-configuration setup
      ansible.builtin.template:
        src: haproxy.service.conf.j2
        dest: "{{ haproxy_systemd_service_unit_override.path }}/haproxy.service.conf"
        mode: 0644
        owner: root
        group: root
      notify: Restart systemd Haproxy

    - name: Remove old HAproxy service file
      ansible.builtin.file:
        path: /etc/systemd/system/haproxy.service
        state: absent
      notify: Restart systemd Haproxy

- name: Remove default HAproxy configs
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/haproxy/haproxy.cfg
    - /etc/haproxy/haproxy.cfg.bak
  notify: Reload HAProxy

- name: Write HAProxy globals and galera configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0664
    owner: haproxy
    group: haproxy
  with_items:
    - { src: '{{ globals_haproxy_template }}', dest: '/etc/haproxy/01-globals.cfg' }
    - { src: '{{ galera_haproxy_template }}', dest: '/etc/haproxy/02-galera.cfg' }
  notify: Restart haproxy

- name: Generate a new Diffie-Hellman group
  ansible.builtin.command: /usr/bin/openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
  when: ssl_keyfile is defined
  args:
    creates: /etc/ssl/private/dhparams.pem
