#!/usr/bin/python

from __future__ import print_function
import argparse
import base64
import csv
import io
import os.path
import sys
import tarfile
from docker import Client


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


class TWImg():
    IMAGES = [
        'teamwire/backend',
        'teamwire/web-screenshot-server',
        'teamwire/notification-server'
    ]

    def __init__(self, registry):
        self.registry = registry
        self.cli = Client(base_url='unix://var/run/docker.sock')

    def _remoteNameFor(self, repo):
        return "{}/{}".format(self.registry, repo)

    def getUntaggedImages(self):
        images = self.cli.images()

        localImages = {}

        for image in images:
            localTags = []
            remoteTags = []
            for tag in image['RepoTags']:
                if tag.startswith(self.registry):
                    remoteTags.append(tag)
                else:
                    localTags.append(tag)

            for tag in localTags:
                if self._remoteNameFor(tag) not in remoteTags:
                    id = image['Id'].split(':')[1]
                    if id not in localImages:
                        localImages[id] = [tag]
                    else:
                        localImages[id].append(tag)

        return localImages

    def pushImagesToRegistry(self, images):
        for ID, repos_and_tags in images.items():
            for repo_and_tag in repos_and_tags:
                print("Tagging %s - %s" % (ID, repo_and_tag))
                repo, tag = repo_and_tag.split(':')

                if self.cli.tag(ID, self._remoteNameFor(repo), tag):
                    self.cli.push(self._remoteNameFor(repo), tag)
                else:
                    eprint("Failed to tag {}".format(repo_and_tag))
                    return 1

    def exportImagestoTarfile(self, filename, tag):
        if not filename:
            eprint("Please specify a file name.")
            return 1

        if not tag:
            eprint("Please specify a tag.")
            return 1

        print("Exporting images to %s:\n" % filename)
        archive = tarfile.open(filename, 'w:gz')

        # Add container images to archive
        files = []
        for image in self.IMAGES:
            containerName = '%s:%s' % (image, tag)
            print(containerName)

            # Ensure the container image is present
            imageList = self.cli.images(image)
            imageTags = sum([img['RepoTags'] for img in imageList], [])

            if containerName not in imageTags:
                eprint("The container image '%s' is not available." % containerName)
                return 1

            # Export the image
            imageFile = io.BytesIO(self.cli.get_image(containerName).data)

            # Append the image to the archive
            fileName = base64.urlsafe_b64encode(containerName)

            info = tarfile.TarInfo(name=fileName)
            imageFile.seek(0, os.SEEK_END)
            info.size = imageFile.tell()
            imageFile.seek(0)
            archive.addfile(tarinfo=info, fileobj=imageFile)
            imageFile.close()

            # Collect metadata
            files.append([fileName, image, tag])

        # Write index file
        indexFile = io.StringIO()
        for f in files:
            indexFile.write(unicode('%s;%s;%s\n' % (f[0], f[1], f[2])))

        indexFileTarInfo = tarfile.TarInfo('index.txt')
        indexFile.seek(0, os.SEEK_END)
        indexFileTarInfo.size = indexFile.tell()
        indexFile.seek(0)
        archive.addfile(tarinfo=indexFileTarInfo, fileobj=indexFile)
        indexFile.close()

        # Finish the archive
        archive.close()

    def importImagesFromTarfile(self, filename):
        if not filename:
            eprint("Please specify a file name.")
            return 1

        if not os.path.isfile(filename):
            eprint("Cannot find %s." % filename)
            return 1

        if not tarfile.is_tarfile(filename):
            eprint("Cannot read %s. Is it a valid archive?" % filename)
            return 1

        print("Importing images from %s:\n" % filename)
        archive = tarfile.open(filename)

        images = {}

        indexFile = archive.extractfile("index.txt")
        indexReader = csv.reader(indexFile, delimiter=';')
        for row in indexReader:
            if len(row) != 3:
                continue

            images[row[0]] = {'repository': row[1], 'tag': row[2]}

        indexFile.close()

        for image, attributes in images.items():
            print("%s:%s" % (attributes['repository'], attributes['tag']))
            imageFile = archive.extractfile(image)

            self.cli.import_image_from_data(
                imageFile.read(),
                attributes['repository'],
                attributes['tag']
            )

            imageFile.close()

    def actionExport(self, args):
        return self.exportImagestoTarfile(args.archive, args.tag)

    def actionImport(self, args):
        return self.importImagesFromTarfile(args.archive)

    def actionPush(self, args):
        if not self.registry:
            eprint("Please specify the registry to push to.")
            return 1

        untaggedImages = self.getUntaggedImages()
        return self.pushImagesToRegistry(untaggedImages)

    def performAction(self, action, args):
        methodName = "action%s" % action.capitalize()
        method = getattr(self, methodName)
        return method(args)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="""Work with Docker images and a local registry"""
    )

    parser.add_argument(
        "--archive",
        dest='archive',
        type=str,
        help='The Docker image export file'
    )

    parser.add_argument(
        "--registry",
        dest='registry',
        type=str,
        help='The Docker registry to use'
    )

    parser.add_argument(
        "--tag",
        dest='tag',
        type=str,
        help='The release tag that will be packaged (export operation)'
    )

    parser.add_argument(
        "action",
        type=str,
        choices=['push', 'import', 'export'],
        help="Action to perform."
    )

    args = parser.parse_args()
    twimg = TWImg(args.registry)
    exit(twimg.performAction(args.action, args))
