---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart MariaDB
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Restart consul
  ansible.builtin.service:
    name: consul
    state: restarted

- name: Set innodb in runtime
  ansible.builtin.command: mysql -e "SET GLOBAL innodb_buffer_pool_size=({{ innodb_buffer_pool_size }} * 1024 * 1024 * 1024);"
  become: true

- name: Set optimizer in runtime
  ansible.builtin.command: mysql -e "SET GLOBAL optimizer_search_depth={{ optimizer_search_depth_value }};"
  become: true
