---
# The below variables define the % of the total CPU or RAM available on each backend server, which a container can util
# The variables are put into a mathemtical equation against the total available resources, in the nomad job file
# Example: backend_cpu_alloc of 0.2 against a total availability of 1GHz, would set the limit to 200Mhz in the job file

# Nomad CPU allocations
backend_cpu_alloc: 0.2 # Default:20%
worker_cpu_alloc: 0.2
notification_cpu_alloc: 0.2
dashboard_cpu_alloc: 0.2
webclient_cpu_alloc: 0.2

# Nomad RAM allocations in MB per CPU core
backend_ram_alloc: 512
backend_ram_alloc_min: "{{ backend_ram_alloc }}"
worker_ram_alloc: 256
worker_ram_alloc_min: "{{ worker_ram_alloc }}"
notification_ram_alloc: 64
notification_ram_alloc_min: "{{ notification_ram_alloc }}"
beat_ram_alloc_min: 384
dashboard_ram_alloc: 256
dashboard_ram_alloc_min: "{{ dashboard_ram_alloc }}"
webclient_ram_alloc: 256
webclient_ram_alloc_min: "{{ dashboard_ram_alloc }}"

# Nomad jobs list
nomad_jobs:
  - teamwire
  - voip
  - dashboard
  - webclient


# Decide which login data to use for docker registry local / harbor / others
local_registry_username: "teamwire"
docker_registry_username: "{{ local_registry_username if groups.docker_registry is defined else dockerhub_username }}"
docker_registry_password: "{{ local_registry_password if groups.docker_registry is defined else dockerhub_password }}"
