# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTS = {
  'lb1' => { :private_ip => '10.0.1.3' },
  'lb2' => { :private_ip => '10.0.1.4' },
  'tw1' => { :private_ip => '10.0.1.5' },
  'tw2' => { :private_ip => '10.0.1.6' },
  'tw3' => { :private_ip => '10.0.1.7' },
  'db1' => { :private_ip => '10.0.1.21' },
  'db2' => { :private_ip => '10.0.1.22' },
  'db3' => { :private_ip => '10.0.1.23' },
}

Vagrant.configure(2) do |config|
  HOSTS.each do |name, conf|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: conf[:private_ip]
    end
  end

  config.vm.box = "teamwire/server"

  # The ssh user name used to connect to the created VM with "vagrant ssh"
  config.ssh.username = "teamwire"

  # Path to the ssh key for that user
  config.ssh.private_key_path = File.expand_path("~/.ssh/teamwire-server-vm-admin")

  # Disable the default shared folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :vmware_fusion do |v|
    v.vmx["memsize"] = "1024"
  end

  config.vm.provider "virtualbox" do |vm|
    vm.customize ["modifyvm", :id, "--memory", "1024"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provider "libvirt" do |vm|
    vm.memory = 1024
  end
end
