- name: Check if the vault secret job token file exists
  ansible.builtin.stat:
    path: "/etc/ansible/job-read.token"
  register: vault_job_token_file

- name: Set the executing host
  ansible.builtin.debug:
    msg: "{{ 'localhost' if groups['all'] | length() == 1 else groups.hashi_servers | sort | first }}"
  register: host_to_delegate

- name: Check if Nomad-job policy exists for Vault
  ansible.builtin.shell: vault policy read nomad-job || true # noqa no-changed-when
  register: policy_job_check
  run_once: true
  delegate_to: "{{ host_to_delegate.msg }}"

- name: Delete possible outdated Nomad-job policy
  ansible.builtin.shell: vault policy delete nomad-job # noqa command-instead-of-shell
  register: revoke_nomad_job_policy
  run_once: true
  delegate_to: "{{ host_to_delegate.msg }}"
  when: not vault_job_token_file.stat.exists

- name: Write/update new vault
  block:
    - name: Write/Update new vault job policy # noqa no-handler
      ansible.builtin.copy:
        src: "{{ role_path }}/../vault/files/{{ item }}"
        dest: /root/
        owner: root
        group: root
        mode: 0644
      with_items:
        - nomad-job-policy.hcl
    - name: Write nomad policy
      ansible.builtin.command: vault policy write nomad-job /root/nomad-job-policy.hcl # noqa no-changed-when
    - name: Remove file
      ansible.builtin.file:
        dest: "/root/{{ item }}"
        state: absent
      with_items:
        - nomad-job-policy.hcl
  run_once: true
  when: revoke_nomad_job_policy.changed
  delegate_to: "{{ host_to_delegate.msg }}"

- name: Ensure valid job token exists
  block:
    - name: Read existing job token from file
      ansible.builtin.slurp:
        src: /etc/ansible/job-read.token
      register: existing_token_raw
      when:
        - vault_job_token_file.stat.exists

    - name: Check job token validity
      ansible.builtin.shell: >
        vault token lookup "{{ existing_token_raw['content'] | b64decode | trim }}"
      register: vault_token_check
      failed_when: false
      changed_when: false
      when:
        - existing_token_raw is defined
        - existing_token_raw['content'] is defined

    - name: Create new job token if old one is invalid or missing
      ansible.builtin.shell: >
        vault token create -policy nomad-job --ttl=72h -renewable=true -format=json | jq -r .auth.client_token
      register: vault_job_read_token
      when:
        - (groups['all'] | length() == 1 or inventory_hostname in groups['hashi_servers'])
        - (vault_token_check.rc is not defined or vault_token_check.rc != 0 or revoke_nomad_job_policy.changed)

    - name: Publish vault job token into token file
      ansible.builtin.copy:
        content: "{{ vault_job_read_token.stdout }}"
        dest: /etc/ansible/job-read.token
        owner: root
        group: root
        mode: '0644'
      when:
        - groups['all'] | length() == 1 or inventory_hostname in groups['hashi_servers']
        - vault_job_read_token is defined
        - vault_job_read_token.stdout is defined

- name: Include renew_job_token
  ansible.builtin.include_tasks: vault_token_renew.yml
  when:
    - groups['all'] | length() == 1
