---
- name: Create Vault user
  ansible.builtin.user:
    name: vault
    shell: /usr/sbin/nologin
    system: true
    home: /var/lib/vault
    state: present

- name: Change audit log permission
  ansible.builtin.file:
    path: /var/log/vault_audit.log
    owner: vault
    group: vault
    state: touch
    mode: 0600

- name: Install logrotate job for vault
  ansible.builtin.copy:
    src: vault-log
    dest: /etc/logrotate.d/vault-log
    owner: root
    group: root
    mode: 0644

- name: Install the Vault binary
  ansible.builtin.unarchive:
    src: /var/cache/downloads/vault_{{ vault_version }}_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    copy: false
  notify: Restart Vault
  when: vault_downloaded.changed or not vault_binary.stat.exists # noqa no-handler

- name: Create Vault directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: vault
    group: vault
  with_items:
    - /etc/vault
    - /var/lib/vault
    - /var/lib/vault/ssl
    - /var/lib/vault/store

- name: Check if Vault certificates
  block:
    - name: Check if Vault certificates exist and are valid
      community.crypto.x509_certificate:
        path: /var/lib/vault/ssl/vault.crt
        provider: assertonly
        has_expired: false
  rescue:
    - name: Debugging SSL certificate
      ansible.builtin.debug:
        msg: "Generating SSL certificates for Vault"
    - name: Include ssl-setup
      ansible.builtin.include_tasks: ssl-setup.yml
  when:
    - ansible_local.vault is defined
    - ansible_local.vault.initialized == "true"

- name: Write Vault config
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault/vault.hcl
    owner: vault
    group: vault
    mode: 0644
  notify: Restart Vault

- name: Vault systemd config
  ansible.builtin.copy:
    src: vault.service
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Vault

- name: Enable the Vault service
  ansible.builtin.service:
    name: vault
    state: started
    enabled: true
    daemon_reload: true

# Handlers should be flushed before any possible bootstrapping
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
