[Service]
CapabilityBoundingSet=~CAP_SYS_TIME CAP_MKNOD CAP_BLOCK_SUSPEND CAP_LEASE CAP_WAKE_ALARM CAP_SYS_MODULE CAP_BPF CAP_SYS_TTY_CONFIG CAP_SYS_PACCT CAP_MAC_OVERRIDE CAP_MAC_ADMIN CAP_SYSLOG CAP_SYS_BOOT CAP_FSETID CAP_SETFCAP CAP_SETPCAP CAP_AUDIT_CONTROL CAP_AUDIT_READ CAP_IPC_OWNER CAP_NET_BROADCAST CAP_NET_RAW CAP_SYS_RAWIO CAP_SYS_PTRACE
DevicePolicy=closed
KeyringMode=private
PrivateMounts=yes
ProcSubset=yes
ProtectClock=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=yes
RestrictAddressFamilies=AF_INET AF_UNIX AF_NETLINK
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @module @obsolete @swap @obsolete @reboot @debug
