---
- name: Check if Nomad-server policy exists for Vault
  ansible.builtin.shell: vault policy read nomad-server || true # noqa no-changed-when
  register: policy_check
  run_once: true
  delegate_to: "{{ groups.hashi_servers | first }}"

- name: Setup Nomad policy
  block:
    - name: Setup the Nomad policy for Vault if it doesn't exist
      ansible.builtin.copy:
        src: "{{ role_path }}/../vault/files/{{ item }}"
        dest: /root/
        owner: root
        group: root
        mode: 0644
      with_items:
        - nomad-server-policy.hcl
        - nomad-job-policy.hcl
        - nomad-cluster-role.json
    - name: Write nomad server policies
      ansible.builtin.command: vault policy write nomad-server /root/nomad-server-policy.hcl # noqa no-changed-when
    - name: Write nomad job policies
      ansible.builtin.command: vault policy write nomad-job /root/nomad-job-policy.hcl # noqa no-changed-when
    - name: Write nomad cluster role
      ansible.builtin.command: vault write /auth/token/roles/nomad-cluster @/root/nomad-cluster-role.json # noqa no-changed-when
    - name: Remove nomad files
      ansible.builtin.file:
        dest: "/root/{{ item }}"
        state: absent
      with_items:
        - nomad-server-policy.hcl
        - nomad-job-policy.hcl
        - nomad-cluster-role.json
  run_once: true
  when:
    - inventory_hostname == groups['hashi_servers'] | first
    - (policy_check.stderr is defined and "No policy" in policy_check.stderr)

- name: Check if the Vault config for Nomad exists
  ansible.builtin.stat:
    path: /etc/nomad/vault.hcl
  register: vault_config

- name: Create Vault token for Nomad
  ansible.builtin.command: vault token create -policy nomad-server -period 72h -orphan -format=json
  when:
    - inventory_hostname in groups['hashi_servers']
    - not vault_config.stat.exists
  register: vault_nomad_token

- name: Set token fact
  ansible.builtin.set_fact:
    vault_nomad_token: "{{ vault_nomad_token.stdout | from_json }}"
  when:
    - inventory_hostname in groups['hashi_servers']
    - not vault_config.stat.exists

- name: Write Vault configuration for nomad
  ansible.builtin.template:
    src: "{{ role_path }}/../vault/templates/nomad-vault.hcl.j2"
    dest: /etc/nomad/vault.hcl
    owner: root
    group: root
    mode: 0644
  notify: Restart Nomad agent
  when: not vault_config.stat.exists
