---
- name: Create Docker Registry storage directory
  file:
    name: "{{ registry_dir }}"
    state: directory
    mode: 0750
  run_once: true

- name: Write Docker registry config file
  template:
    src: "{{ registry_config }}"
    dest: "{{ registry_dir }}/config.yml"
  run_once: true
  notify: restart registry container

- name: Get information about docker-registry
  docker_container_info:
    name: docker-registry
  register: result

- name: Check if docker-registry needs to be updated
  debug:
    msg: "Registry needs to be updated"
  when:
    - result.exists == true
    - result.container.State.Running == true
    - "result.container.Config.Image != registry_version"
  changed_when:
    - "result.container.Config.Image != registry_version"
  notify: restart registry container
  
- name: Check if docker-registry is available and running
  debug:
    msg: "Container not available or running"
  when:
    - result.exists == false or result.container.State.Running == false
  changed_when:
    - result.exists == false or result.container.State.Running == false
  notify: restart registry container

# Push all local images to the local registry
- name: Copy the registry image helper tool
  copy:
    src: twimg
    dest: /usr/local/bin/
    mode: 0755
