---
- name: Create Docker Registry storage directory
  ansible.builtin.file:
    name: "{{ registry_dir }}"
    state: directory
    mode: 0750
  run_once: true

- name: Install necessary package to create credentials
  ansible.builtin.package:
    name: apache2-utils
    state: present

- name: Stat local registry password file
  ansible.builtin.stat:
    path: "{{ registry_dir }}/htpasswd"
  changed_when: not stat_local_registry_htpasswd.stat.exists
  register: stat_local_registry_htpasswd
  notify: Create local registry credentials

- name: Write Docker registry config file
  ansible.builtin.template:
    src: "{{ registry_config }}"
    dest: "{{ registry_dir }}/config.yml"
    owner: root
    group: root
    mode: 0644
  run_once: true
  notify: Restart registry

- name: Local registry container
  community.docker.docker_container:
    name: docker-registry
    image: "{{ registry_version }}"
    state: started
    restart_policy: always
    network_mode: host
    log_driver: syslog
    log_options:
      tag: docker-registry
      syslog-facility: local6
    volumes: "{{ registry_dir }}:/var/lib/registry,{{ registry_dir }}/config.yml:/etc/docker/registry/config.yml"
    env:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: "/var/lib/registry/htpasswd"

# Push all local images to the local registry
- name: Copy the registry image helper tool
  ansible.builtin.copy:
    src: twimg
    dest: /usr/local/bin/
    mode: 0755
