---
- name: Import requirements which needs to run first
  import_playbook: playbooks/requirements.yml

- name: Ask for additional information upfront
  hosts: hashi_servers:local
  tasks:
    - name: Ask for additional information
      ansible.builtin.include_role:
        name: "{{ inventory_dir }}/roles/vault"
        tasks_from: gather_information.yml

- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - management

- name: Deploy and configure external storage client
  hosts: all
  roles:
    - role: storage_client
      when: external_storage_path is defined

- name: Deploy Vault secret system
  hosts: all
  roles:
    - role: vault
      when: config_done is defined

- name: Deploy and configure MySQL database
  hosts: all
  roles:
    - role: db
      when:
        - config_done is defined
        - mysql_host is not defined
        - oracle_host is not defined

- name: Deploy and configure Redis database
  hosts: all
  roles:
    - role: redis
      when: config_done is defined

- name: Deploy and configure the backend server
  hosts: all
  roles:
    - role: docker
    - role: backend
      when: config_done is defined
    - role: voip
      when:
        - config_done is defined
        - enable_voip is defined
        - enable_voip | string() == 'true'
    - role: go
      when: config_done is defined
    - role: frontend
      when: config_done is defined

- name: Deploy monitoring services
  hosts: all
  roles:
    - role: monitoring
      when:
        - config_done is defined
        - enable_monitoring is defined

- name: Run security and housekeeping job to remove unused dependencies
  hosts: all
  roles:
    - role: security
      when: config_done is defined
    - role: housekeeping
      when: config_done is defined

- name: Clean up database users
  hosts: all
  gather_facts: false
  tasks:
    - name: Get variables for teamwire db users
      ansible.builtin.include_vars:
        file: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname) }}/roles/db/defaults/main.yml"

    - name: Get variables for monitoring db users
      ansible.builtin.import_role:
        name: monitoring
        tasks_from: database-configuration

    - name: Cleanup mysql users
      ansible.builtin.import_role:
        name: housekeeping
        tasks_from: clean_mysql_users
      when:
        - config_done is defined
        - mysql_host is not defined
        - oracle_host is not defined

- name: Set current tag (COMPLETE) in /etc/platform_version
  hosts: all
  tasks:
    - name: Set tag
      ansible.builtin.copy:
        dest: /etc/platform_version
        content: '{{ current_local_tag }}'
        owner: root
        group: root
        mode: 0644
      when: packer_build_name is not defined
