---
- name: Reload NFS server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: reloaded

- name: Restart NFS server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
