local_registry_username: "teamwire"
docker_registry_username: "{{ local_registry_username if groups.docker_registry is defined else dockerhub_username }}"
docker_registry_password: "{{ local_registry_password if groups.docker_registry is defined else dockerhub_password }}"
