---
# CIS - BENCHMARK IDS: 2500,2501,2502,2503,2504,2505,2506
- name: Ensure mounting of additional filesystems is disabled
  ansible.builtin.copy:
    src: mountfs.conf
    dest: "/etc/modprobe.d/mounts.conf"
    mode: 0640
    owner: root
    group: root
  notify:
    - Unload fs modules
    - Restart kernel modules systemd

# CIS - BENCHMARK ID: 2676 cis: 5.4.5
- name: Harden bash
  block:
    - name: Set TMOUT in /etc/profile
      ansible.builtin.lineinfile:
        dest: "/etc/profile"
        line: "readonly TMOUT=900 ; export TMOUT"
        state: present
    - name: Set TMOUT in /etc/bash.bashrc
      ansible.builtin.lineinfile:
        dest: "/etc/bash.bashrc"
        line: "readonly TMOUT=900 ; export TMOUT"
        state: present

# CIS - BENCHMARK ID: 2682 cis: 6.1.6
- name: Harden passwd-
  ansible.builtin.file:
    name: /etc/passwd-
    owner: root
    group: root
    mode: u-x,go-rwx

# CIS - BENCHMARK ID: 2684 cis: 6.1.8
- name: Harden group-
  ansible.builtin.file:
    name: /etc/group-
    owner: root
    group: root
    mode: u-x,go-rwx

# CIS - BENCHMARK ID: 2669 cis: 5.3.4
# See:
# https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#pam-default-password


# CIS - BENCHMARK tmp disk
- name: Include tmp_disk
  ansible.builtin.include_tasks: tmp_disk.yml
  when: enable_tmp_mount | default(false) | bool
# CIS - BENCHMARK sshd hardening
- name: Include sshd-hardening
  ansible.builtin.include_tasks: sshd-hardening.yml
# CIS - BENCHMARK cronjobs
- name: Include cronjob
  ansible.builtin.include_tasks: cronjob.yml

# CIS - BENCHMARK ID: 29691 cis: 6.1.5
- name: Harden shadow
  ansible.builtin.file:
    name: /etc/shadow
    owner: root
    group: root
    mode: u-x,g-wx,o-rwx

# CIS - BENCHMARK ID: 29692 cis: 6.1.6
- name: Harden shadow-
  ansible.builtin.file:
    name: /etc/shadow-
    owner: root
    group: root
    mode: u-x,g-wx,o-rwx

# CIS - BENCHMARK ID: 29693 cis: 6.1.7
- name: Harden gshadow
  ansible.builtin.file:
    name: /etc/gshadow
    owner: root
    group: root
    mode: u-x,g-wx,o-rwx

# CIS - BENCHMARK ID: 29694 cis: 6.1.8
- name: Harden gshadow-
  ansible.builtin.file:
    name: /etc/gshadow-
    owner: root
    group: root
    mode: u-x,g-wx,o-rwx

- name: Configure sudo to use sudo log
  ansible.builtin.copy:
    src: 10-log-file
    dest: "/etc/sudoers.d/10-log-file"
    mode: 0440
    owner: root
    group: root
    validate: /usr/sbin/visudo -cf %s

