---

# ------------------------------------------------------------------------------
# [ITOPS-3652] Implement libpam-tmpdir
# ------------------------------------------------------------------------------
- name: Install libpam-tmpdir
  ansible.builtin.apt:
    name: libpam-tmpdir
    state: present

- name: Enable tmpdir via pam-auth-update
  ansible.builtin.command:
    cmd: pam-auth-update --enable tmpdir
  changed_when: false

# ------------------------------------------------------------------------------
# [ITOPS-6197] Enable audit module for pam sshd configuration
# ------------------------------------------------------------------------------
- name: Deploy pam sshd configuration
  ansible.builtin.copy:
    src: pamd-sshd
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: '0644'
  notify: Reload sshd
