---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart redis
  ansible.builtin.service:
    name: redis-server
    state: restarted

- name: Reload consul
  ansible.builtin.service:
    name: consul
    state: reloaded
